name: logo
on:
  schedule:
    - cron:  '42 1 * * *'
permissions:
  contents: write
jobs:
  update_logo:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: logo
      - name: Setup conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: "3.12"
      - name: install packages
        run: |
          conda install matplotlib
          pip install -v --no-deps https://github.com/rnajena/sugar/archive/refs/heads/master.zip
      - name: create logo
        run: |
          sugar logo sugar_logo.png
          sugar logo sugar_logo_transparent.png --transparent
          sugar logo sugar_logo_dark.png --transparent --color1 0.8 --color2 0.5
      - name: commit logo
        run: |
          git config --global user.name 'trichter'
          git config --global user.email 'trichter@users.noreply.github.com'
          git add sugar_logo*.png
          # git commit -am "daily update of logo"
          # git push
          git commit -a --amend --no-edit
          git push -f
      - name: trigger ReadTheDocs build
        run: |
          curl -X POST -d "token=${{ secrets.READTHEDOCS_DEPLOY_TOKEN }}" ${{ secrets.READTHEDOCS_DEPLOY_URL }}
