name: tests
on:
  push:
  pull_request:
    branches:
      # only branches from forks which have the form 'user:branch-name'
      - '**:**'
  schedule:
    - cron:  '42 0 * * 0'
jobs:
  run_minimal_test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v4
      - name: Setup conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: "3.12"
      - name: print conda environment info
        run: |
          conda info -a
          conda list
      - name: install package
        run: |
          pip install -v --no-deps .
      - name: check that package works
        run: |
          mkdir empty; cd empty
          sugar -h
          python -c "from sugar import read; print(read())"
  run_tests:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python: ["3.11", "3.12"]
        options: [""]
        include:
          - os: macos-latest
            python: "3.12"
          - os: ubuntu-latest
            python: "3.12"
            options: full
          - os: ubuntu-latest
            python: "3.12"
            options: full warnings
          - os: ubuntu-latest
            python: "3.12"
            options: subset
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ contains(matrix.options, 'warnings') }}
    env:
      # set additional runtest options (--web, -W error)
      test_options: ${{ contains(matrix.options, 'full') && '--web' || '' }} ${{ contains(matrix.options, 'warnings') && '-W error' || '' }}
      # set additional dependencies for full test
      deps: ${{ contains(matrix.options, 'full') && 'matplotlib pandas platformdirs seaborn requests biopython tqdm' || ''  }}
      depspip: ${{ contains(matrix.options, 'full') && 'binarysearchfile' || contains(matrix.options, 'subset') && 'binarysearchfile' || ''  }}
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v4
      - name: Setup conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: ${{ matrix.python }}
      - name: install dependencies
        run: |
          conda install -y pytest pytest-cov ${{ env.deps }}
      - name: install pip dependencies
        if: contains(matrix.options, 'full') || contains(matrix.options, 'subset')
        run:
          pip install ${{ env.depspip }}
      - name: print conda environment info
        run: |
          conda info -a
          conda list
      - name: install package
        run: |
          pip install -v --no-deps .
      - name: run test suite
        run: |
          mkdir empty; cd empty
          sugar test --cov sugar --cov-report=xml:$PWD/coverage.xml --cov-append ${{ env.test_options }}
      - name: upload coverage
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # required
          fail_ci_if_error: true
